FROM clojure:openjdk-8-tools-deps-1.10.0.414-alpine

RUN apk --no-cache add git make nodejs yarn

MAINTAINER Jakub Sokolowski "jakub@status.im"
LABEL description="Basic image with Clojure for building in CI."

ENTRYPOINT []
